# Generated by Django 3.0 on 2021-05-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210518_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.IntegerField(choices=[('Reception', ((11, 'Réceptionniste'), (12, 'Chef de réception'))), ('Salle', ((21, "Maître d'hôtel"), (22, 'Serveur(se)'), (23, 'Sommelier'), (24, 'Barman'))), ('Entretien', ((31, 'Femme de chambre'), (32, 'Maçon'), (33, 'Plombier'), (34, 'Electricien'))), ('Restauration', ((41, 'Cuisinier'), (42, 'Chef de cuisine'), (43, 'Patissier'))), ('Sécurité', ((51, 'Agent de sécurité'), (52, 'Chef de sécurité'), (53, 'Spécialiste caméras')))]),
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.URLField(),
        ),
    ]
