# Generated by Django 3.0 on 2021-05-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='CV',
            new_name='cv_file',
        ),
    ]
