# Generated by Django 3.0 on 2021-05-19 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_auto_20210519_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='cv_file',
            field=models.FileField(upload_to='CV_files/'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
